image: registry.znuny.com/znuny/internal/docker-otrs6ci:$OTRS_TAG

stages:
  - test

mysql:
  stage: test
  services:
    - name: registry.znuny.com/znuny/internal/docker-mysql:$MYSQL_TAG
      alias: mysql
  script:
    - /run.sh
    - su -c "/opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-EscalationSuspend.sopm" -s /bin/bash otrs
    - /unittest.sh
