image: otrs5ci

before_script:
  - env
  - pwd
  - /run.sh
  - su -c "/opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-EscalationSuspend.sopm" -s /bin/bash otrs

stages:
  - test

job_unit_otrs_Znuny4OTRSEscalationSuspend:
  stage: test
  script:
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --test EscalationSuspend" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --test EscalationSuspendLoop" -s /bin/bash otrs
