image: otrs4ci

before_script:
  - env
  - pwd
  - /run.sh
  - su -c "perl /opt/otrs/bin/znuny.AdvancedPackageManagerInstallSOPM.pl /opt/otrs/Znuny4OTRS-EscalationSuspend.sopm" -s /bin/bash otrs

stages:
  - test

job_unit_otrs_Znuny4OTRSEscalationSuspend:
  stage: test
  script:
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n EscalationSuspend" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n EscalationSuspendLoop" -s /bin/bash otrs
